
#Advancements Tracker (Client configuration)
[general]
	#List of default tracked advancements, mostly used by mod packs.
	trackedAdvancements = [""]

["Advancements Tracker: Overview"]
	#Enable/Disable the advancements overview screen.
	overviewEnabled = true

["Advancements Tracker: Widget"]
	#Enable/Disable the advancements tracker widget.
	widgetEnabled = true
	#Shows the widget automatically. If this is set to false the widget will be only visible after pressing the defined hot-keys.
	widgetVisible = true
	#Defines the base position of the widget, default is MIDDLE_RIGHT
	#Allowed Values: BOTTOM_LEFT, BOTTOM_RIGHT, MIDDLE_LEFT, MIDDLE_RIGHT, TOP_LEFT, TOP_RIGHT
	widgetPosition = "MIDDLE_RIGHT"
	#Defines the max. height of the widget. Default is 0 which mean use the max. available height.
	#Range: 0 ~ 600
	widgetHeight = 0
	#Defines the max.width of the widget.
	#Range: 120 ~ 600
	widgetWidth = 135
	#Defines the top position relative to the widget position.
	#Range: -400 ~ 400
	widgetTop = 0
	#Defines the left position relative to the widget position.
	#Range: -400 ~ 400
	widgetLeft = 0

[Debug]
	#Changed the default log level to get more output.
	logLevel = "info"

[cache]
	trackedAdvancementsRemote = [""]
	trackedAdvancementsLocal = [""]

