
["Allowed Experience Fluids"]
	#Add IDs of fluids you want the obelisk to support here in the form mod_id:fluid_name
	AllowedFluids = ["mob_grinding_utils:fluid_xp", "cofh_core:experience", "industrialforegoing:essence"]

["Experience Obelisk Capacity"]
	#The fluid capacity of the obelisk in mB. Default = 100000000, Max = 2147483647
	Capacity = 100000000

