
#Basin related properties
[basin]
	#If enabled, when interacting with this block it will dispense free water into
	#it's fluid tank, assuming the tank is empty or contains water but has not reached it's
	#capacity.
	dispenseWater = false
	#The storage capacity of the fluid tank contained in this block. If you're using Forge,
	#1000 units represents the capacity of a bucket, while it's 81000 on Fabric. So if you
	#want 3 buckets worth of storage, it will be 3000 (Forge) or 243000 (Fabric)
	fluidCapacity = 1000

#Toilet related properties
[toilet]
	#The storage capacity of the fluid tank contained in this block. If you're using Forge,
	#1000 units represents the capacity of a bucket, while it's 81000 on Fabric. So if you
	#want 3 buckets worth of storage, it will be 3000 (Forge) or 243000 (Fabric)
	fluidCapacity = 1000
	#If enabled, when interacting with this block it will dispense free water into
	#it's fluid tank, assuming the tank is empty or contains water but has not reached it's
	#capacity.
	dispenseWater = false

#Electricity related properties
[electricity]
	#The maximum amount of nodes in a network that can be powered by an electricity
	#source, like the electricity generator.
	maximumNodesInNetwork = 64
	#The maximum amount of links that can be connected to an Electricity Generator.
	maximumLinksPerElectricityGenerator = 12
	#The amount of power that is generated by the electricity generator per fuel tick.
	#For example, coal has 1600 ticks of fuel, and at a ratio of 4, it would produce
	#6400 units of power. The default value of 8 means that the electricity generator
	#would consume almost 2 coal per in-game day.
	fuelToPowerRatio = 64
	#The maximum area radius determines the size of the area which electricity nodes must
	#be inside of to be powered by a source node (like the Electricity Generator). The
	#radius is represented as blocks. The center of the area is the source node providing
	#the power, and area radius expands in each cardinal direction, including up and down.
	#For example, if we have an area radius of 16 blocks, a source node can provide power
	#to other electricity nodes from (x-16,y-16,z-16) to (x+16,y+16,z+16) with x,y,z being
	#the block position of the source. Electricity nodes still must be connected with
	#links to be powered, this config value just determines the acceptable area.
	powerableAreaRadius = 80
	#The maximum amount of links that can be connected to a single electricity node.
	maximumLinksPerElectricityNode = 6

	#Cheats for electricity. Free power, etc.
	[electricity.cheats]
		#Electricity Generators will now output free power, and stay on forever.
		freeGeneratorPower = true
		#Makes all blocks that require electricity always be powered without them being
		#connected to an Electricity Generator. Warning, some blocks may no longer work as
		#expected. Use at your own risk of a downgraded experience.
		everythingIsPowered = false

#Mailing related properties
[mailing]
	#The amount of inventory rows in a mailbox. If you change this value from a larger to
	#a smaller value, items contained in the removed rows will be deleted. Use caution
	#when changing this value to avoid inconvenience and backup your saves.
	mailboxInventoryRows = 1
	#The maximum amount of mailboxes a player is allowed to register/own.
	maxMailboxesPerPlayer = 16
	#A list of dimensions you are allowed to place mailboxes. An empty list means that
	#mailboxes can be placed in any dimension.
	#An example of how the list is defined:
	#allowedDimensions = [
	#    "minecraft:overworld",
	#    "minecraft:the_nether",
	#    ...
	#]
	#^ Note: This is just an example. Write your list below.
	allowedDimensions = []
	#Prevents items contained in this list from being sent through a Post Box.
	#An example of how the list is defined:
	#bannedItems = [
	#    "minecraft:water_bucket",
	#    "minecraft:diamond",
	#    "refurbished_furniture:mailbox"
	#    ...
	#]
	#^ Note: This is just an example. Write your list below.
	bannedItems = []
	#If enabled, this will ban items with an inventory (like a Shulker Box) being sent through
	#a Post Box. This prevents players from creating massive NBT on a single item, which can
	#cause issues for your server/world save.
	banSendingItemsWithInventories = true
	#The maximum amount of items that can be queued for delivery to a mailbox. Items become
	#queued when the receiving mailbox's inventory is full. This is to prevent infinite storage.
	deliveryQueueSize = 32

#Bath related properties
[bath]
	#If enabled, when interacting with this block it will dispense free water into
	#it's fluid tank, assuming the tank is empty or contains water but has not reached it's
	#capacity.
	dispenseWater = false
	#The storage capacity of the fluid tank contained in this block. If you're using Forge,
	#1000 units represents the capacity of a bucket, while it's 81000 on Fabric. So if you
	#want 3 buckets worth of storage, it will be 3000 (Forge) or 243000 (Fabric)
	fluidCapacity = 10000

#Kitchen Sink related properties
[kitchenSink]
	#The storage capacity of the fluid tank contained in this block. If you're using Forge,
	#1000 units represents the capacity of a bucket, while it's 81000 on Fabric. So if you
	#want 3 buckets worth of storage, it will be 3000 (Forge) or 243000 (Fabric)
	fluidCapacity = 3000
	#If enabled, when interacting with this block it will dispense free water into
	#it's fluid tank, assuming the tank is empty or contains water but has not reached it's
	#capacity.
	dispenseWater = true

#Recycle Bin related properties
[recycleBin]
	#The maximum amount of experience levels that the recycling bin can hold. Recycling stops once it reaches that level.
	maximumExperienceLevels = 5
	#The amount of time in ticks that it takes to perform one cycle of recycling
	processingTime = 10
	#The amount of experience to add when recycling an item.
	experiencePerItem = 0.05

#Trampoline related properties
[trampoline]
	#The maximum height that can be achieved from bouncing on the trampoline. The maximum
	#height is affected the shape of the trampoline, the center trampoline in a 3x3 will
	#be able to reach the maximum bounce height, while a single trampoline will only reach
	#half.
	maxBounceHeight = 8.0

