
["Spawn Biome Utility Control Values"]
	#Debug Level: 0 = Off, 1 = Log, 2 = Chat+Log
	#Range: 0 ~ 2
	debugLevel = 0
	#generateReport
	generateReport = true
	#suppressMinecraftMobReporting
	suppressMinecraftMobReporting = false
	#fixEmptyNether
	fixEmptyNether = true
	#Use the 'BiomeMobWeight.csv' file to balance Biome spawn values
	balanceBiomeSpawnValues = true
	#Fix min, max values and add nether creatures
	fixSpawnValues = true
	#Use the 'StructMobWeight.csv' file to balance structure spawn values
	balanceStructureSpawnValues = true
	#Mod Name set separated by SemiColons of mods to report.
	includedReportModsSet = "exampleModName;"

["Spawn Weight Values"]
	#minimum Spawn Weight
	#Range: 1 ~ 1000
	minSpawnWeight = 10
	#maximum Spawn Weight
	#Range: 1 ~ 1000
	maxSpawnWeight = 80
	#list of Mod:MobName,DefaultSpawnweight;
	defaultSpawnWeightList = "minecraft:enderman,5;minecraft:witch,5;"

