
[misc]
	creative_tab = false
	cross_section_world_mode = false
	#Range: 1 ~ 128
	diamond_grindstone_deplete_chance = 20
	enable_rough_gems = true
	enable_raw_nuggets = true

[nether_portals]
	flint_and_steel_portal_lighting = true
	crying_obsidian_dimensional_tears = true
	respawn_anchor_dimensional_tears = true
	portal_destruction_crying_obsidian = true
	piglins_give_crying_obsidian = true
	portal_creation_sound = true
	portal_destruction_sound = true

[worldgen]
	stone_stripe_features = true
	enable_sporophytes = true
	dark_forest_portabellas = true
	enable_mores = true

[slimes]
	increased_slime_spawn_rate = false
	#Range: 1 ~ 2400
	slime_eat_cooldown = 150
	enable_slime_growth = true
	#Range: 1 ~ 127
	slime_growth_chance = 10
	#Range: 1 ~ 127
	slime_growth_max = 5
	slime_cauldrons = true
	slimes_friendly_if_regen = true
	slimes_always_friendly = false

[utilities]
	#Range: 1 ~ 128
	hammer_chisel_charge_time = 20
	sculk_drops_with_shears = true
	#Range: 1 ~ 128
	echo_fork_range = 16
	#Range: 1 ~ 72000
	echo_cooldown = 600
	#Range: 1 ~ 72000
	echo_glow_durration = 1200
	#Range: 1 ~ 32
	magnet_range = 8
	#Range: 1 ~ 512
	magnetite_range = 128

